@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.teamabode.greenery.mixin;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;